name: macos-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{env.INSTALL_LOCATION}}
        key: ${{matrix.os}}-dependencies
    - name: Get Conan
      if: ${{ steps.cache.output.cache-hit != 'true' }}
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@4dc7e6dd45c8b1e02e909979d7cfc5ebba6ddbe2
      uses: turtlebrowser/get-conan@v1.0
    - name: Install ninja-build tool
      if: ${{ steps.cache.output.cache-hit != 'true' }}
      # You may pin to the exact commit or the version.
      # uses: seanmiddleditch/gha-setup-ninja@16b940825621068d98711680b6c3ff92201f8fc0
      uses: seanmiddleditch/gha-setup-ninja@v3
      with:
        # Version of ninja-build to install
        version: # default is 1.10.0
        # Override default platform with one of [win, mac, linux]
        platform: mac # optional
        # Destination directory, will be added to PATH
        destination: ${{env.INSTALL_LOCATION}} # optional, default is ninja-build
        # Proxy server
        http_proxy: # optional
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j4 --target all --verbose
